# Generated by Django 3.0.7 on 2022-10-24 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('movil', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.TextField()),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('funcion', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Enfermero', 'Enfermero'), ('Medico', 'Medico'), ('Obrero', 'Obrero')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField()),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Encargado')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('movil', models.CharField(blank=True, max_length=11, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Enfermero', 'Enfermero'), ('Medico', 'Medico'), ('Obrero', 'Obrero')], max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
                ('existencia', models.IntegerField()),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('observacion', models.TextField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Establecimiento')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Reposos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_reposo', models.TextField()),
                ('duracion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('status', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=20)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('observacion', models.TextField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Salida')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vacunas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingreso', models.IntegerField()),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ingreso')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vacunas')),
            ],
        ),
    ]
