# Generated by Django 3.0.7 on 2022-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='rol_sistema',
            field=models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Coordinador/a de cuarto frio', 'Coordinador/a de cuarto frio'), ('Coordinador/a de division estrategica', 'Coordinador/a de division estrategica'), ('Transcriptor', 'Transcriptor')], max_length=50, null=True),
        ),
    ]
