# Generated by Django 3.0.7 on 2022-11-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_ci',
            field=models.CharField(choices=[('V', 'V-'), ('E', 'E-')], default='V', max_length=10),
            preserve_default=False,
        ),
    ]
