# Generated by Django 3.0.7 on 2022-10-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221012_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reposos',
            name='tipo_reposo',
        ),
        migrations.DeleteModel(
            name='TipoReposo',
        ),
    ]
