# Generated by Django 3.0.7 on 2022-10-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221014_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reposos',
            name='motivo_reposo',
            field=models.TextField(),
        ),
    ]
