# Generated by Django 3.0.7 on 2022-10-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221015_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposos',
            name='status',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Aprobado', max_length=20),
            preserve_default=False,
        ),
    ]
