# Generated by Django 3.0.7 on 2022-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reposos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='ocupacion',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Enfermero', 'Enfermero'), ('Medico', 'Medico'), ('Obrero', 'Obrero')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20),
        ),
    ]
